#This is for the EC2 instance, simple nginx setup to proxy the requests to the Rails app.
server {
    listen 80;

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# For HTTPS, certbot would be used to get the certificate and then nginx would be configured to use it, but a domain is required for that.